#include <stan/math/rev.hpp>
#include <test/unit/math/rev/util.hpp>
#include <test/unit/util.hpp>
#include <gtest/gtest.h>
#include <stdexcept>

TEST_F(AgradRev, fma_rvalue_operands_moved_onto_arena) {
  using stan::math::fma;
  using stan::math::var;
  using vec_v = Eigen::Matrix<var, Eigen::Dynamic, 1>;
  auto grad_sum = [](const auto& res) {
    stan::math::set_zero_all_adjoints();
    stan::math::sum(res).grad();
  };
  // a moved operand is kept alive on the var_alloc_stack_, a copy is not
  const auto& moved = stan::math::ChainableStack::instance_->var_alloc_stack_;
  Eigen::VectorXd x_val(3);
  x_val << 1.5, -2, 3;
  Eigen::VectorXd y_val(3);
  y_val << 0.5, 4, -1;
  Eigen::VectorXd z_val(3);
  z_val << -1, 0.25, 2;
  vec_v x = x_val;
  vec_v y = y_val;
  vec_v z = z_val;
  Eigen::VectorXd expected = x_val.array() * y_val.array() + z_val.array();

  std::size_t n_moved = moved.size();
  vec_v res = fma(vec_v(x), vec_v(y), vec_v(z));
  EXPECT_EQ(n_moved + 3, moved.size());
  EXPECT_MATRIX_FLOAT_EQ(expected, res.val());
  grad_sum(res);
  EXPECT_MATRIX_FLOAT_EQ(y_val, x.adj());
  EXPECT_MATRIX_FLOAT_EQ(x_val, y.adj());
  EXPECT_MATRIX_FLOAT_EQ(Eigen::VectorXd::Ones(3), z.adj());

  // fma(b2, x2, fma(b1, x1, alpha)) as generated by stanc3 --O1
  var b1 = 2;
  var b2 = -1;
  var alpha = 0.5;
  n_moved = moved.size();
  res = fma(b2, y_val, fma(b1, x_val, alpha));
  EXPECT_EQ(n_moved + 1, moved.size());
  EXPECT_MATRIX_FLOAT_EQ(-1 * y_val.array() + 2 * x_val.array() + 0.5,
                         res.val());
  grad_sum(res);
  EXPECT_FLOAT_EQ(x_val.sum(), b1.adj());
  EXPECT_FLOAT_EQ(y_val.sum(), b2.adj());
  EXPECT_FLOAT_EQ(3, alpha.adj());

  // an rvalue of doubles is moved too and read in the reverse pass
  n_moved = moved.size();
  res = fma(b1, Eigen::VectorXd(x_val), z);
  EXPECT_EQ(n_moved + 1, moved.size());
  grad_sum(res);
  EXPECT_FLOAT_EQ(x_val.sum(), b1.adj());
  EXPECT_MATRIX_FLOAT_EQ(Eigen::VectorXd::Ones(3), z.adj());

  // lvalues are copied and stay usable
  n_moved = moved.size();
  res = fma(x, y, z);
  EXPECT_EQ(n_moved, moved.size());
  EXPECT_EQ(3, x.size());
  EXPECT_EQ(3, z.size());
}

TEST_F(AgradRev, fma_rvalue_operands_size_mismatch) {
  using stan::math::fma;
  using vec_v = Eigen::Matrix<stan::math::var, Eigen::Dynamic, 1>;
  vec_v a = Eigen::VectorXd::Ones(3);
  vec_v b = Eigen::VectorXd::Ones(4);
  EXPECT_THROW(fma(vec_v(a), vec_v(b), vec_v(a)), std::invalid_argument);
  EXPECT_THROW(fma(vec_v(a), vec_v(a), vec_v(b)), std::invalid_argument);
  EXPECT_THROW(fma(stan::math::var(1), vec_v(a), vec_v(b)),
               std::invalid_argument);
}
